#cloud-config
users:
  -  name: dima
     groups: sudo
     shell: /bin/bash
     sudo: ["ALL=(ALL) NOPASSWD:ALL"]
     ssh_authorized_keys:
       - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID95JJEbprAb8RWzIpN1+sskJrq26BhMKUgy65qqg4wd dima@ws-HP
